[package]

name = "rdb"
version = "0.2.0"
authors = ["Jan-Erik Rediger <badboy@fnordig.de>"]

keywords = ["redis", "database"]
description = "Fast and efficient RDB parsing utility"

readme = "README.md"
license = "MIT"

homepage = "http://rdb.fnordig.de/"
documentation = "http://rdb.fnordig.de/doc/rdb/"
repository = "https://github.com/badboy/rdb-rs"

[[bin]]
name = "rdb"
path = "src/main.rs"
doc  = false

[dependencies]
lzf = "*"
clap = "*"
rustc-serialize = "*"
regex = "*"
byteorder = "*"
