name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: setup toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      
      - name: cargo build
        run: cargo build --verbose
      
      - name: cargo test
        run: cargo test --verbose

      - name: Check formatting
        if: matrix.toolchain == 'stable'
        run: cargo fmt --all -- --check

      - name: Clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy --all --all-features --tests -- -D warnings
